version: 2

updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "semiannually"
    ignore:
      - dependency-name: "tailwindcss"
      - dependency-name: "tailwind-merge"
      