name: Build Check

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install

    - name: Set repo owner lower
      id: repo_owner
      run: echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build --platform linux/amd64 \
          -t ghcr.io/${{ steps.repo_owner.outputs.owner }}/tentix:${{ github.sha }} \
          .

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ steps.repo_owner.outputs.owner }}/tentix:${{ github.sha }}